language: rust
dist: trusty
sudo: required
rust:
- beta
- nightly
- stable

cache:
  directories:
  - target

os:
  - linux
#  - osx

addons:
   apt:
      packages:
      - clang

before_script:
- make -f travis-build/Makefile prepare-rustfmt

script:
- export PATH="./librocksdb_sys/crocksdb/:$PATH"
- curl -L http://goo.gl/iUW1u2 -o ./librocksdb_sys/crocksdb/clang-format-diff.py
- format-diff.sh && cargo fmt --write-mode diff && cd librocksdb_sys && cargo fmt --write-mode diff || (echo please make format and run tests before creating a pr!; exit 1)
- cargo build --features static-link
- cargo test --all --features static-link

env:
  global:
  - RUST_TEST_THREADS=1
  - LD_LIBRARY_PATH: "/usr/local/lib"
  - RUSTFMT_VERSION=v0.6.0
