sudo: false
language: rust

rust: nightly
os:
  - linux
  - osx
env:
  - BUILD_TYPE=dynamic COMPILER=g++-4.8
  - BUILD_TYPE=static COMPILER=g++-4.8
  - BUILD_TYPE=dynamic COMPILER=clang++
  - BUILD_TYPE=static COMPILER=clang++

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['g++-4.8', 'zlib1g-dev', 'libbz2-dev', 'libsnappy-dev', 'curl', 'libdw-dev', 'libelf-dev', 'elfutils', 'binutils-dev']

matrix:
  exclude:
    - os: linux
      env: BUILD_TYPE=dynamic COMPILER=clang++
    - os: linux
      env: BUILD_TYPE=static COMPILER=clang++
    - os: osx
      env: BUILD_TYPE=dynamic COMPILER=g++-4.8
    - os: osx
      env: BUILD_TYPE=static COMPILER=g++-4.8

install:
  - export LOCAL_DIR=$HOME/.cache/
  - export PATH=$PATH:$LOCAL_DIR/bin
  - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$LOCAL_DIR/lib
  - export LIBRARY_PATH=${LIBRARY_PATH}:$LOCAL_DIR/lib
  - export DYLD_LIBRARY_PATH=${DY_LIBRARY_PATH}:$LOCAL_DIR/lib
  - make -f travis-build/Makefile prepare_${TRAVIS_OS_NAME}_${BUILD_TYPE}

script:
  - make -f travis-build/Makefile test_${TRAVIS_OS_NAME}_${BUILD_TYPE}

